IMPORT LIBRARIES

In [1]:
import pandas as pd
import numpy as np

LOAD THE DATASET

In [12]:
df=pd.read_csv("../data/raw/telecom_customer_churn.csv")

In [15]:
df.head()

,CustomerID,Gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,MonthlyDataUsageGB,NumberOfComplaints,SatisfactionScore,AvgCallDuration,Churn
0,CUST112628,Male,1.0,Yes,No,47.0,Yes,No phone service,No,Yes,...,Two year,Yes,Bank transfer,103.36,4849.03,NaN,11.0,2.0,16.6,No
1,CUST137730,Female,1.0,No,No,23.0,Yes,No,DSL,No internet service,...,Two year,No,Electronic check,83.15,1941.71,177.9,3.0,6.0,22.6,No
2,CUST139991,Female,1.0,No,No,49.0,Yes,No,No,No internet service,...,One year,No,Credit card,23.39,1222.92,NaN,9.0,4.0,40.6,No
3,CUST108525,Male,1.0,Yes,No,34.0,No,No,Fiber optic,No,...,One year,Yes,Bank transfer,29.37,713.69,NaN,7.0,6.0,34.8,No
4,CUST108279,Male,1.0,No,No,18.0,No,Yes,Fiber optic,Yes,...,Month-to-month,No,Bank transfer,117.52,2192.19,NaN,1.0,2.0,12.1,No

In [14]:
df.tail()

,CustomerID,Gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,MonthlyDataUsageGB,NumberOfComplaints,SatisfactionScore,AvgCallDuration,Churn
59995,CUST154343,Female,1.0,Yes,Yes,37.0,Yes,Yes,DSL,No internet service,...,Two year,Yes,Mailed check,49.96,1967.53,190.1,NaN,2.0,33.0,No
59996,CUST138158,Male,1.0,Yes,Yes,27.0,Yes,No phone service,Fiber optic,Yes,...,Month-to-month,No,Mailed check,87.86,2474.11,NaN,8.0,2.0,NaN,Yes
59997,CUST100860,Female,1.0,Yes,Yes,31.0,No,Yes,Fiber optic,No,...,Month-to-month,No,Electronic check,104.34,3393.82,NaN,9.0,7.0,59.4,No
59998,CUST115795,Male,0.0,Yes,No,56.0,No,Yes,No,No,...,Two year,Yes,Credit card,87.71,4992.92,267.7,4.0,2.0,41.5,No
59999,CUST156422,Male,0.0,Yes,No,20.0,No,No,No,No internet service,...,Two year,No,Mailed check,22.12,517.49,152.8,6.0,2.0,37.2,No

CREATE A COPY

In [20]:
df_understanding=df.copy()

CHECK DATASET SHAPE

In [21]:
df_understanding.shape

(60000, 25)

VIEW SAMPLE DATA

In [22]:
df_understanding.head()

,CustomerID,Gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,MonthlyDataUsageGB,NumberOfComplaints,SatisfactionScore,AvgCallDuration,Churn
0,CUST112628,Male,1.0,Yes,No,47.0,Yes,No phone service,No,Yes,...,Two year,Yes,Bank transfer,103.36,4849.03,NaN,11.0,2.0,16.6,No
1,CUST137730,Female,1.0,No,No,23.0,Yes,No,DSL,No internet service,...,Two year,No,Electronic check,83.15,1941.71,177.9,3.0,6.0,22.6,No
2,CUST139991,Female,1.0,No,No,49.0,Yes,No,No,No internet service,...,One year,No,Credit card,23.39,1222.92,NaN,9.0,4.0,40.6,No
3,CUST108525,Male,1.0,Yes,No,34.0,No,No,Fiber optic,No,...,One year,Yes,Bank transfer,29.37,713.69,NaN,7.0,6.0,34.8,No
4,CUST108279,Male,1.0,No,No,18.0,No,Yes,Fiber optic,Yes,...,Month-to-month,No,Bank transfer,117.52,2192.19,NaN,1.0,2.0,12.1,No

In [23]:
df_understanding.tail()

,CustomerID,Gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,MonthlyDataUsageGB,NumberOfComplaints,SatisfactionScore,AvgCallDuration,Churn
59995,CUST154343,Female,1.0,Yes,Yes,37.0,Yes,Yes,DSL,No internet service,...,Two year,Yes,Mailed check,49.96,1967.53,190.1,NaN,2.0,33.0,No
59996,CUST138158,Male,1.0,Yes,Yes,27.0,Yes,No phone service,Fiber optic,Yes,...,Month-to-month,No,Mailed check,87.86,2474.11,NaN,8.0,2.0,NaN,Yes
59997,CUST100860,Female,1.0,Yes,Yes,31.0,No,Yes,Fiber optic,No,...,Month-to-month,No,Electronic check,104.34,3393.82,NaN,9.0,7.0,59.4,No
59998,CUST115795,Male,0.0,Yes,No,56.0,No,Yes,No,No,...,Two year,Yes,Credit card,87.71,4992.92,267.7,4.0,2.0,41.5,No
59999,CUST156422,Male,0.0,Yes,No,20.0,No,No,No,No internet service,...,Two year,No,Mailed check,22.12,517.49,152.8,6.0,2.0,37.2,No

In [24]:
df_understanding.sample(5)

,CustomerID,Gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,MonthlyDataUsageGB,NumberOfComplaints,SatisfactionScore,AvgCallDuration,Churn
55036,CUST112297,Male,1.0,Yes,No,66.0,Yes,No phone service,Fiber optic,No internet service,...,Month-to-month,No,Electronic check,79.78,5276.70,191.6,2.0,3.0,51.2,No
41471,CUST121950,Female,0.0,Yes,No,54.0,No,No phone service,Fiber optic,No internet service,...,Month-to-month,Yes,Electronic check,111.48,6040.25,473.9,NaN,9.0,47.1,No
10823,CUST132704,Female,0.0,Yes,Yes,14.0,No,Yes,DSL,Yes,...,Month-to-month,Yes,Electronic check,75.83,413.79,NaN,7.0,2.0,31.0,No
45665,CUST150369,Female,0.0,Yes,Yes,54.0,Yes,No,Fiber optic,Yes,...,Two year,No,Mailed check,54.80,2608.43,83.0,6.0,10.0,26.4,No
52138,CUST113798,NaN,1.0,NaN,No,61.0,Yes,No,No,No internet service,...,Month-to-month,Yes,Electronic check,43.21,2444.15,280.1,6.0,9.0,8.2,No

CHECK COLUMN NAMES

In [25]:
df_understanding.columns

Index(['CustomerID', 'Gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'Tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'MonthlyDataUsageGB',
       'NumberOfComplaints', 'SatisfactionScore', 'AvgCallDuration', 'Churn'],
      dtype='str')

In [26]:
for column in df_understanding.columns:
    print(column)

CustomerID
Gender
SeniorCitizen
Partner
Dependents
Tenure
PhoneService
MultipleLines
InternetService
OnlineSecurity
OnlineBackup
DeviceProtection
TechSupport
StreamingTV
StreamingMovies
Contract
PaperlessBilling
PaymentMethod
MonthlyCharges
TotalCharges
MonthlyDataUsageGB
NumberOfComplaints
SatisfactionScore
AvgCallDuration
Churn

CHECK DATA TYPE

In [27]:
df_understanding.info()

<class 'pandas.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Data columns (total 25 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   CustomerID          60000 non-null  str
 1   Gender              57546 non-null  str
 2   SeniorCitizen       60000 non-null  float64
 3   Partner             57181 non-null  str
 4   Dependents          56702 non-null  str
 5   Tenure              57931 non-null  float64
 6   PhoneService        60000 non-null  str
 7   MultipleLines       56213 non-null  str
 8   InternetService     58029 non-null  str
 9   OnlineSecurity      53485 non-null  str
 10  OnlineBackup        54703 non-null  str
 11  DeviceProtection    55452 non-null  str
 12  TechSupport         52789 non-null  str
 13  StreamingTV         53955 non-null  str
 14  StreamingMovies     53125 non-null  str
 15  Contract            57757 non-null  str
 16  PaperlessBilling    56964 non-null  str
 17  PaymentMethod       56445 non-null  str
 18  MonthlyCharges      57365 non-null  float64
 19  TotalCharges        56968 non-null  float64
 20  MonthlyDataUsageGB  51381 non-null  float64
 21  NumberOfComplaints  49909 non-null  float64
 22  SatisfactionScore   52552 non-null  float64
 23  AvgCallDuration     50877 non-null  float64
 24  Churn               60000 non-null  str
dtypes: float64(8), str(17)
memory usage: 11.4 MB

CHECK MISSING VALUES

In [28]:
df_understanding.isnull().sum()

CustomerID                0
Gender                 2454
SeniorCitizen             0
Partner                2819
Dependents             3298
Tenure                 2069
PhoneService              0
MultipleLines          3787
InternetService        1971
OnlineSecurity         6515
OnlineBackup           5297
DeviceProtection       4548
TechSupport            7211
StreamingTV            6045
StreamingMovies        6875
Contract               2243
PaperlessBilling       3036
PaymentMethod          3555
MonthlyCharges         2635
TotalCharges           3032
MonthlyDataUsageGB     8619
NumberOfComplaints    10091
SatisfactionScore      7448
AvgCallDuration        9123
Churn                     0
dtype: int64

In [37]:
df_understanding.isnull().mean()*100

CustomerID             0.000000
Gender                 4.090000
SeniorCitizen          0.000000
Partner                4.698333
Dependents             5.496667
Tenure                 3.448333
PhoneService           0.000000
MultipleLines          6.311667
InternetService        3.285000
OnlineSecurity        10.858333
OnlineBackup           8.828333
DeviceProtection       7.580000
TechSupport           12.018333
StreamingTV           10.075000
StreamingMovies       11.458333
Contract               3.738333
PaperlessBilling       5.060000
PaymentMethod          5.925000
MonthlyCharges         4.391667
TotalCharges           5.053333
MonthlyDataUsageGB    14.365000
NumberOfComplaints    16.818333
SatisfactionScore     12.413333
AvgCallDuration       15.205000
Churn                  0.000000
dtype: float64

CHECK DUPLICATE ROWS

In [32]:
df_understanding.duplicated().sum()

np.int64(900)

In [33]:
df_understanding.nunique()

CustomerID            59100
Gender                    2
SeniorCitizen             2
Partner                   2
Dependents                2
Tenure                   73
PhoneService              2
MultipleLines             3
InternetService           3
OnlineSecurity            3
OnlineBackup              3
DeviceProtection          3
TechSupport               3
StreamingTV               3
StreamingMovies           3
Contract                  3
PaperlessBilling          2
PaymentMethod             4
MonthlyCharges        10115
TotalCharges          51311
MonthlyDataUsageGB     5118
NumberOfComplaints       13
SatisfactionScore        10
AvgCallDuration         620
Churn                     2
dtype: int64

UNDERSTAND THE TARGET COLUMN

In [ ]:
df_understanding["Churn"].value_counts()
#DATA IS IMBALANCED

Churn
No     52328
Yes     7672
Name: count, dtype: int64

In [36]:
df_understanding["Churn"].value_counts(normalize=True)*100

Churn
No     87.213333
Yes    12.786667
Name: proportion, dtype: float64

SEPARATE NUMERICAL AND CATEGORICAL COLUMNS

In [44]:
num_data = [
    "SeniorCitizen",
    "Tenure",
    "MonthlyCharges",
    "TotalCharges",
    "MonthlyDataUsageGB",
    "NumberOfComplaints",
    "SatisfactionScore",
    "AvgCallDuration"
]

In [45]:
cat_data = [
    "Gender",
    "Partner",
    "Dependents",
    "PhoneService",
    "MultipleLines",
    "InternetService",
    "OnlineSecurity",
    "OnlineBackup",
    "DeviceProtection",
    "TechSupport",
    "StreamingTV",
    "StreamingMovies",
    "Contract",
    "PaperlessBilling",
    "PaymentMethod"
]

In [46]:
id_data = [
    "CustomerID"
]

In [47]:
target = "Churn"

In [48]:
df_understanding[num_data].describe()

,SeniorCitizen,Tenure,MonthlyCharges,TotalCharges,MonthlyDataUsageGB,NumberOfComplaints,SatisfactionScore,AvgCallDuration
count,60000.000000,57931.000000,57365.000000,56968.000000,51381.000000,49909.000000,52552.000000,50877.000000
mean,0.483017,36.130362,69.744703,2454.443156,249.909087,5.013264,5.482037,30.558970
std,0.499716,21.026648,28.923593,1930.875359,144.462950,3.187287,2.859730,16.921215
min,0.000000,0.000000,18.660000,0.000000,0.000000,0.000000,1.000000,0.000000
25%,0.000000,18.000000,44.640000,901.865000,125.400000,2.000000,3.000000,16.100000
50%,0.000000,36.000000,69.430000,2011.895000,248.800000,5.000000,5.000000,30.600000
75%,1.000000,54.000000,94.830000,3645.790000,375.500000,8.000000,8.000000,45.100000
max,1.000000,72.000000,122.320000,9397.990000,518.100000,12.000000,10.000000,61.900000

In [49]:
df_understanding[cat_data].describe()

,Gender,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod
count,57546,57181,56702,60000,56213,58029,53485,54703,55452,52789,53955,53125,57757,56964,56445
unique,2,2,2,2,3,3,3,3,3,3,3,3,3,2,4
top,Female,Yes,Yes,No,No phone service,No,No,No internet service,Yes,No,Yes,No internet service,Month-to-month,Yes,Electronic check
freq,28932,28659,28364,30875,18923,19493,18030,18441,18731,17892,18033,17891,31426,28661,14349