In [47]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("../data/raw/telecom_customer_churn.csv")

In [3]:
df_preprocessed=df.copy()

In [4]:
df_preprocessed.isnull().sum()

CustomerID                0
Gender                 2454
SeniorCitizen             0
Partner                2819
Dependents             3298
Tenure                 2069
PhoneService              0
MultipleLines          3787
InternetService        1971
OnlineSecurity         6515
OnlineBackup           5297
DeviceProtection       4548
TechSupport            7211
StreamingTV            6045
StreamingMovies        6875
Contract               2243
PaperlessBilling       3036
PaymentMethod          3555
MonthlyCharges         2635
TotalCharges           3032
MonthlyDataUsageGB     8619
NumberOfComplaints    10091
SatisfactionScore      7448
AvgCallDuration        9123
Churn                     0
dtype: int64

In [5]:
df_preprocessed.duplicated().sum()

np.int64(900)

In [6]:
df_preprocessed = df_preprocessed.drop_duplicates()

In [7]:
df_preprocessed.duplicated().sum()

np.int64(0)

In [8]:
df_preprocessed.isnull().sum()

CustomerID               0
Gender                2417
SeniorCitizen            0
Partner               2780
Dependents            3247
Tenure                2038
PhoneService             0
MultipleLines         3734
InternetService       1943
OnlineSecurity        6428
OnlineBackup          5221
DeviceProtection      4480
TechSupport           7112
StreamingTV           5955
StreamingMovies       6790
Contract              2211
PaperlessBilling      2992
PaymentMethod         3493
MonthlyCharges        2595
TotalCharges          2992
MonthlyDataUsageGB    8487
NumberOfComplaints    9944
SatisfactionScore     7324
AvgCallDuration       9006
Churn                    0
dtype: int64

In [9]:
num_data = [
    "Tenure",
    "MonthlyCharges",
    "TotalCharges",
    "MonthlyDataUsageGB",
    "NumberOfComplaints",
    "SatisfactionScore",
    "AvgCallDuration"
]

In [10]:
cat_data = [
    "Gender",
    "Partner",
    "Dependents",
    "MultipleLines",
    "InternetService",
    "OnlineSecurity",
    "OnlineBackup",
    "DeviceProtection",
    "TechSupport",
    "StreamingTV",
    "StreamingMovies",
    "Contract",
    "PaperlessBilling",
    "PaymentMethod"
]

In [11]:
from sklearn.impute import SimpleImputer

In [12]:
imp_cat_data=SimpleImputer(strategy="most_frequent")
df_preprocessed[cat_data]=imp_cat_data.fit_transform(df_preprocessed[cat_data])

In [14]:
imp_num_data=SimpleImputer(strategy="mean")

df_preprocessed[num_data]=imp_num_data.fit_transform(df_preprocessed[num_data])

In [15]:
df_preprocessed.isnull().sum()

CustomerID            0
Gender                0
SeniorCitizen         0
Partner               0
Dependents            0
Tenure                0
PhoneService          0
MultipleLines         0
InternetService       0
OnlineSecurity        0
OnlineBackup          0
DeviceProtection      0
TechSupport           0
StreamingTV           0
StreamingMovies       0
Contract              0
PaperlessBilling      0
PaymentMethod         0
MonthlyCharges        0
TotalCharges          0
MonthlyDataUsageGB    0
NumberOfComplaints    0
SatisfactionScore     0
AvgCallDuration       0
Churn                 0
dtype: int64

In [17]:
df_preprocessed.duplicated().sum()

np.int64(0)

In [18]:
df_preprocessed.dtypes

CustomerID                str
Gender                    str
SeniorCitizen         float64
Partner                   str
Dependents                str
Tenure                float64
PhoneService              str
MultipleLines             str
InternetService           str
OnlineSecurity            str
OnlineBackup              str
DeviceProtection          str
TechSupport               str
StreamingTV               str
StreamingMovies           str
Contract                  str
PaperlessBilling          str
PaymentMethod             str
MonthlyCharges        float64
TotalCharges          float64
MonthlyDataUsageGB    float64
NumberOfComplaints    float64
SatisfactionScore     float64
AvgCallDuration       float64
Churn                     str
dtype: object

In [19]:
df_preprocessed.info()

<class 'pandas.DataFrame'>
Index: 59100 entries, 0 to 59999
Data columns (total 25 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   CustomerID          59100 non-null  str
 1   Gender              59100 non-null  str
 2   SeniorCitizen       59100 non-null  float64
 3   Partner             59100 non-null  str
 4   Dependents          59100 non-null  str
 5   Tenure              59100 non-null  float64
 6   PhoneService        59100 non-null  str
 7   MultipleLines       59100 non-null  str
 8   InternetService     59100 non-null  str
 9   OnlineSecurity      59100 non-null  str
 10  OnlineBackup        59100 non-null  str
 11  DeviceProtection    59100 non-null  str
 12  TechSupport         59100 non-null  str
 13  StreamingTV         59100 non-null  str
 14  StreamingMovies     59100 non-null  str
 15  Contract            59100 non-null  str
 16  PaperlessBilling    59100 non-null  str
 17  PaymentMethod       59100 non-null  str
 18  MonthlyCharges      59100 non-null  float64
 19  TotalCharges        59100 non-null  float64
 20  MonthlyDataUsageGB  59100 non-null  float64
 21  NumberOfComplaints  59100 non-null  float64
 22  SatisfactionScore   59100 non-null  float64
 23  AvgCallDuration     59100 non-null  float64
 24  Churn               59100 non-null  str
dtypes: float64(8), str(17)
memory usage: 11.7 MB

In [20]:
df_preprocessed["CustomerID"].head()

0    CUST112628
1    CUST137730
2    CUST139991
3    CUST108525
4    CUST108279
Name: CustomerID, dtype: str

In [21]:
df_preprocessed = df_preprocessed.drop(columns=["CustomerID"])

In [22]:
df_preprocessed.columns

Index(['Gender', 'SeniorCitizen', 'Partner', 'Dependents', 'Tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges', 'MonthlyDataUsageGB',
       'NumberOfComplaints', 'SatisfactionScore', 'AvgCallDuration', 'Churn'],
      dtype='str')

In [23]:
for column in df_preprocessed.columns:
    print(column)

Gender
SeniorCitizen
Partner
Dependents
Tenure
PhoneService
MultipleLines
InternetService
OnlineSecurity
OnlineBackup
DeviceProtection
TechSupport
StreamingTV
StreamingMovies
Contract
PaperlessBilling
PaymentMethod
MonthlyCharges
TotalCharges
MonthlyDataUsageGB
NumberOfComplaints
SatisfactionScore
AvgCallDuration
Churn

Separate Features (X) and Target (y).

In [95]:
x=df_preprocessed.drop(columns=["Churn"])
y=df_preprocessed["Churn"]

In [96]:
x.shape

(59100, 23)

In [97]:
y.shape

(59100,)

In [98]:
x.head()

,Gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,...,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,MonthlyDataUsageGB,NumberOfComplaints,SatisfactionScore,AvgCallDuration
0,Male,1.0,Yes,No,47.0,Yes,No phone service,No,Yes,Yes,...,Yes,Two year,Yes,Bank transfer,103.36,4849.03,249.967536,11.0,2.0,16.6
1,Female,1.0,No,No,23.0,Yes,No,DSL,No internet service,No,...,No internet service,Two year,No,Electronic check,83.15,1941.71,177.900000,3.0,6.0,22.6
2,Female,1.0,No,No,49.0,Yes,No,No,No internet service,No,...,No internet service,One year,No,Credit card,23.39,1222.92,249.967536,9.0,4.0,40.6
3,Male,1.0,Yes,No,34.0,No,No,Fiber optic,No,Yes,...,No internet service,One year,Yes,Bank transfer,29.37,713.69,249.967536,7.0,6.0,34.8
4,Male,1.0,No,No,18.0,No,Yes,Fiber optic,Yes,Yes,...,No,Month-to-month,No,Bank transfer,117.52,2192.19,249.967536,1.0,2.0,12.1

In [99]:
y.head()

0    No
1    No
2    No
3    No
4    No
Name: Churn, dtype: str

In [31]:
from sklearn.model_selection import train_test_split

In [101]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [102]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(47280, 23)
(11820, 23)
(47280,)
(11820,)

In [103]:
y_train.value_counts()

Churn
No     41250
Yes     6030
Name: count, dtype: int64

In [104]:
y_test.value_counts()

Churn
No     10298
Yes     1522
Name: count, dtype: int64

In [36]:
cat_data = [
    "Gender",
    "Partner",
    "Dependents",
    "PhoneService",
    "MultipleLines",
    "InternetService",
    "OnlineSecurity",
    "OnlineBackup",
    "DeviceProtection",
    "TechSupport",
    "StreamingTV",
    "StreamingMovies",
    "Contract",
    "PaperlessBilling",
    "PaymentMethod"
]

In [37]:
from sklearn.preprocessing import OneHotEncoder

In [38]:
encoder = OneHotEncoder(drop="first", handle_unknown="ignore", sparse_output=False)

In [39]:
x_train_cat = encoder.fit_transform(x_train[cat_data])

In [40]:
x_test_cat = encoder.transform(x_test[cat_data])

In [64]:
num_data = [
    "SeniorCitizen",
    "Tenure",
    "MonthlyCharges",
    "TotalCharges",
    "MonthlyDataUsageGB",
    "NumberOfComplaints",
    "SatisfactionScore",
    "AvgCallDuration"
]

In [65]:
from sklearn.preprocessing import StandardScaler

In [66]:
scaler = StandardScaler()

In [67]:
x_train_num = scaler.fit_transform(x_train[num_data])

In [68]:
x_test_num = scaler.transform(x_test[num_data])

In [70]:
x_train_final = np.hstack([x_train_num, x_train_cat])

In [71]:
x_test_final = np.hstack([x_test_num, x_test_cat])

In [72]:
cat_columns = encoder.get_feature_names_out(cat_data)

In [73]:
final_columns = list(num_data) + list(cat_columns)

In [74]:
x_train_final = pd.DataFrame(
    x_train_final,
    columns=final_columns,
    index=x_train.index
)

In [75]:
x_train_final.head()

,SeniorCitizen,Tenure,MonthlyCharges,TotalCharges,MonthlyDataUsageGB,NumberOfComplaints,SatisfactionScore,AvgCallDuration,Gender_Male,Partner_Yes,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card,PaymentMethod_Electronic check,PaymentMethod_Mailed check
50656,-0.966713,-1.553738,-1.297624,-1.176414,0.086924,-0.347029,-1.675887,0.217469,0.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
12506,1.034433,0.622166,0.170474,0.641692,1.385558,2.060580,1.311657,0.146865,1.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19159,-0.966713,-0.151489,-0.535159,-0.425859,-1.222911,-0.003085,0.938214,-0.616939,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1134,1.034433,-0.586669,0.003692,-0.852189,-1.446942,-0.347029,-0.182115,1.603869,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
13852,-0.966713,0.380399,0.117878,0.276368,0.552909,1.372692,-0.929001,-1.130421,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [76]:
x_test_final = pd.DataFrame(
    x_test_final,
    columns=final_columns,
    index=x_test.index
)

In [78]:
x_test_final.head()

,SeniorCitizen,Tenure,MonthlyCharges,TotalCharges,MonthlyDataUsageGB,NumberOfComplaints,SatisfactionScore,AvgCallDuration,Gender_Male,Partner_Yes,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card,PaymentMethod_Electronic check,PaymentMethod_Mailed check
17548,-0.966713,0.000036,0.003692,-1.303081,-0.000690,0.001946,-0.001589,0.002856,0.0,1.0,...,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
48454,-0.966713,0.912287,-0.923451,0.133011,-1.754611,0.340859,-1.302444,-1.618229,1.0,1.0,...,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
3960,1.034433,1.154054,-0.608229,0.342035,-0.000690,-1.722806,-0.001589,0.002856,1.0,1.0,...,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0
26403,1.034433,-0.441609,1.590565,0.350800,0.341573,0.340859,0.191328,0.002856,1.0,1.0,...,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
15330,1.034433,0.235339,1.617745,1.444386,-0.000690,0.340859,-0.555558,-1.066236,0.0,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

both training + testing data in one CSV

In [79]:
train_data = pd.concat([x_train_final, y_train], axis=1)
test_data = pd.concat([x_test_final, y_test], axis=1)

final_data = pd.concat([train_data, test_data])

In [105]:
final_data.to_csv(
    "../data/processed/telecom_churn_processed.csv",
    index=False
)