In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("../data/raw/customer_churn_telecom.csv")

In [3]:
df.head()

,CustomerID,Gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,MonthlyDataUsageGB,NumberOfComplaints,SatisfactionScore,AvgCallDuration,Churn
0,CUST000001,Male,1.0,Yes,Yes,41.0,Yes,Yes,DSL,No,...,Month-to-month,Yes,Electronic check,114.79,4706.39,473.7,10.0,10.0,56.9,Yes
1,CUST000002,Male,1.0,No,Yes,50.0,Yes,No phone service,DSL,No internet service,...,Month-to-month,Yes,Bank transfer,24.96,1248.00,48.7,1.0,10.0,4.5,No
2,CUST000003,Female,1.0,No,No,26.0,Yes,Yes,No,Yes,...,Month-to-month,No,Credit card,69.64,1810.64,144.0,1.0,2.0,31.2,No
3,CUST000004,Male,0.0,No,No,21.0,No,No phone service,DSL,No internet service,...,Month-to-month,Yes,Electronic check,95.71,2009.91,365.6,4.0,10.0,59.6,No
4,CUST000005,Male,1.0,No,Yes,57.0,Yes,No,Fiber optic,Yes,...,Month-to-month,No,Credit card,48.46,2762.22,40.3,7.0,7.0,33.4,No

In [4]:
df.tail()

,CustomerID,Gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,MonthlyDataUsageGB,NumberOfComplaints,SatisfactionScore,AvgCallDuration,Churn
50495,CUST011970,Male,0.0,Yes,No,15.0,Yes,No,No,No internet service,...,Two year,No,Credit card,57.81,867.15,426.0,4.0,8.0,37.8,No
50496,CUST016682,Female,1.0,Yes,No,17.0,No,Yes,DSL,No internet service,...,Month-to-month,Yes,Electronic check,89.41,1519.97,194.1,8.0,3.0,4.1,No
50497,CUST005633,Male,1.0,Yes,Yes,32.0,Yes,No,Fiber optic,Yes,...,One year,Yes,Bank transfer,44.25,1416.00,92.4,8.0,10.0,29.4,No
50498,CUST040298,Female,0.0,Yes,Yes,49.0,Yes,No,Fiber optic,No,...,One year,Yes,Mailed check,71.79,3517.71,68.1,10.0,10.0,32.8,No
50499,CUST003724,Male,0.0,Yes,No,19.0,Yes,No phone service,DSL,Yes,...,Month-to-month,No,Mailed check,29.31,556.89,90.8,8.0,1.0,44.9,No

In [5]:
df.shape

(50500, 25)

In [6]:
df.columns

Index(['CustomerID', 'Gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'Tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'MonthlyDataUsageGB',
       'NumberOfComplaints', 'SatisfactionScore', 'AvgCallDuration', 'Churn'],
      dtype='str')

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50500 entries, 0 to 50499
Data columns (total 25 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   CustomerID          48992 non-null  str
 1   Gender              48992 non-null  str
 2   SeniorCitizen       48992 non-null  float64
 3   Partner             48992 non-null  str
 4   Dependents          48992 non-null  str
 5   Tenure              48992 non-null  float64
 6   PhoneService        48992 non-null  str
 7   MultipleLines       48992 non-null  str
 8   InternetService     48992 non-null  str
 9   OnlineSecurity      48992 non-null  str
 10  OnlineBackup        48992 non-null  str
 11  DeviceProtection    48992 non-null  str
 12  TechSupport         48992 non-null  str
 13  StreamingTV         48992 non-null  str
 14  StreamingMovies     48992 non-null  str
 15  Contract            48992 non-null  str
 16  PaperlessBilling    48992 non-null  str
 17  PaymentMethod       48992 non-null  str
 18  MonthlyCharges      48992 non-null  float64
 19  TotalCharges        48992 non-null  float64
 20  MonthlyDataUsageGB  48992 non-null  float64
 21  NumberOfComplaints  48992 non-null  float64
 22  SatisfactionScore   48992 non-null  float64
 23  AvgCallDuration     48992 non-null  float64
 24  Churn               50500 non-null  str
dtypes: float64(8), str(17)
memory usage: 9.6 MB

In [8]:
df.describe()

,SeniorCitizen,Tenure,MonthlyCharges,TotalCharges,MonthlyDataUsageGB,NumberOfComplaints,SatisfactionScore,AvgCallDuration
count,48992.000000,48992.000000,48992.000000,48992.000000,48992.000000,48992.000000,48992.000000,48992.000000
mean,0.500939,36.095056,69.968392,2528.580143,250.125839,5.004899,5.484426,30.597849
std,0.500004,21.090690,28.791328,1908.102509,144.353682,3.160808,2.871671,16.969792
min,0.000000,0.000000,20.000000,20.030000,0.000000,0.000000,1.000000,1.000000
25%,0.000000,18.000000,44.977500,995.025000,125.400000,2.000000,3.000000,15.900000
50%,1.000000,36.000000,69.790000,2080.000000,249.850000,5.000000,5.000000,30.800000
75%,1.000000,54.000000,94.970000,3702.645000,375.300000,8.000000,8.000000,45.200000
max,1.000000,72.000000,120.000000,8636.400000,500.000000,10.000000,10.000000,60.000000

In [9]:
df.dtypes

CustomerID                str
Gender                    str
SeniorCitizen         float64
Partner                   str
Dependents                str
Tenure                float64
PhoneService              str
MultipleLines             str
InternetService           str
OnlineSecurity            str
OnlineBackup              str
DeviceProtection          str
TechSupport               str
StreamingTV               str
StreamingMovies           str
Contract                  str
PaperlessBilling          str
PaymentMethod             str
MonthlyCharges        float64
TotalCharges          float64
MonthlyDataUsageGB    float64
NumberOfComplaints    float64
SatisfactionScore     float64
AvgCallDuration       float64
Churn                     str
dtype: object

In [10]:
df.nunique()

CustomerID            48500
Gender                    2
SeniorCitizen             2
Partner                   2
Dependents                2
Tenure                   73
PhoneService              2
MultipleLines             3
InternetService           3
OnlineSecurity            3
OnlineBackup              3
DeviceProtection          3
TechSupport               3
StreamingTV               3
StreamingMovies           3
Contract                  3
PaperlessBilling          2
PaymentMethod             4
MonthlyCharges         9922
TotalCharges          43032
MonthlyDataUsageGB     5001
NumberOfComplaints       11
SatisfactionScore        10
AvgCallDuration         591
Churn                     2
dtype: int64